[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración para permitir métodos POST en rutas API
[dev]
  command = "npm run dev"
  targetPort = 3000
  autoLaunch = false
